### PR TITLE
fixed click handler for video gallery items

### PR DESCRIPTION
**Pull request by mtyeh411**
the only change is L846 & L871...all others were from `master` branch of `blueimp/Gallery`

pull request to `blueimp/Gallery` is here
https://github.com/blueimp/Gallery/pull/200

### CODE REVIEW

**Comment by mtyeh411** [comment]
@bernabas please review

**Comment by mtyeh411** [comment]
DO NOT MERGE

**Comment by mtyeh411** [comment]
@bernabas ready for review

**Comment by mtyeh411** [comment]
will be needed as a part of 9.1-Patch-B JIRA
https://weddingwire.atlassian.net/browse/WW-27912
https://github.com/weddingwire/weddingwire-ng/pull/5120

**Comment by bernabas** [comment]
@chancedowns :+1:

**Pull request merged**
